'use client'

import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { Comp, MarketAnalysis, PropertyLead, ArvMethod } from '@/hooks/use-deals-store'

export interface ARVReportData {
  property: {
    id: string
    address: string
    city: string
    state: string
    zip: string
    sqft: number | null
    bedrooms: number | null
    bathrooms: number | null
    yearBuilt: number | null
  }
  calculation: {
    method: ArvMethod
    baseArv: number
    adjustments: {
      feature: number
      condition: number
    }
    finalArv: number
    confidence: {
      score: number
      breakdown: {
        compCount: number
        recency: number
        priceVariance: number
        adjustmentSpread: number
      }
    }
  }
  comps: Array<{
    address: string
    salePrice: number
    saleDate: string
    bedrooms?: number
    bathrooms?: number
    sqft?: number
    pricePerSqft?: number
    totalAdjustment: number
  }>
  notes: string
  generatedAt: string
  generatedBy: string
}

// Helper to format currency for text output
function formatCurrencyText(value: number | null): string {
  if (value === null || value === undefined) return '$0'
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value)
}

// Helper to format date
function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}

// Generate text summary for clipboard
export function generateARVSummary(data: ARVReportData): string {
  const methodLabel = data.calculation.method.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())
  
  return `
ARV ANALYSIS SUMMARY
=====================

PROPERTY INFORMATION
Address: ${data.property.address}
City: ${data.property.city}, ${data.property.state} ${data.property.zip}
Square Feet: ${data.property.sqft?.toLocaleString() || 'N/A'}
Bedrooms: ${data.property.bedrooms || 'N/A'}
Bathrooms: ${data.property.bathrooms || 'N/A'}
Year Built: ${data.property.yearBuilt || 'N/A'}

ARV CALCULATION
Method: ${methodLabel}
Base ARV: ${formatCurrencyText(data.calculation.baseArv)}
Feature Adjustment: ${data.calculation.adjustments.feature >= 0 ? '+' : ''}${formatCurrencyText(data.calculation.adjustments.feature)}
Condition Adjustment: ${data.calculation.adjustments.condition >= 0 ? '+' : ''}${formatCurrencyText(data.calculation.adjustments.condition)}
-----------------
FINAL ARV: ${formatCurrencyText(data.calculation.finalArv)}

CONFIDENCE ANALYSIS
Overall Score: ${data.calculation.confidence.score}% (${data.calculation.confidence.score >= 75 ? 'High' : data.calculation.confidence.score >= 60 ? 'Good' : data.calculation.confidence.score >= 40 ? 'Medium' : 'Low'})
- Comp Count: ${data.calculation.confidence.breakdown.compCount}/25
- Sale Recency: ${data.calculation.confidence.breakdown.recency}/25  
- Price Consistency: ${data.calculation.confidence.breakdown.priceVariance}/25
- Comp Similarity: ${data.calculation.confidence.breakdown.adjustmentSpread}/25

COMPARABLE SALES (${data.comps.length} properties)
${data.comps.map((comp, i) => 
  `${i + 1}. ${comp.address}
   Sale Price: ${formatCurrencyText(comp.salePrice)}
   Sale Date: ${formatDate(comp.saleDate)}
   Size: ${comp.sqft?.toLocaleString() || 'N/A'} sq ft
   Bed/Bath: ${comp.bedrooms || '?'}/${comp.bathrooms || '?'}
   Price/SF: ${comp.pricePerSqft ? `$${Math.round(comp.pricePerSqft)}` : 'N/A'}
   Adjustments: ${comp.totalAdjustment >= 0 ? '+' : ''}${formatCurrencyText(comp.totalAdjustment)}`
).join('\n\n')}

${data.notes ? `NOTES\n${data.notes}` : ''}

Generated: ${formatDate(data.generatedAt)}
Report ID: ${data.property.id}

---
Generated by Rehab Planner Pro - ARV Calculator
`.trim()
}

// Copy text to clipboard
export async function copyARVToClipboard(data: ARVReportData): Promise<boolean> {
  try {
    const summary = generateARVSummary(data)
    await navigator.clipboard.writeText(summary)
    return true
  } catch (error) {
    console.error('Failed to copy to clipboard:', error)
    return false
  }
}

// Generate PDF report
export async function generateARVPDF(data: ARVReportData, elementId?: string): Promise<Blob | null> {
  try {
    // If elementId provided, capture that element
    if (elementId) {
      const element = document.getElementById(elementId)
      if (!element) {
        throw new Error('Element not found for PDF generation')
      }
      
      const canvas = await html2canvas(element, {
        scale: 2, // Higher quality
        useCORS: true,
        allowTaint: true
      })
      
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      })
      
      const imgWidth = 210 // A4 width in mm
      const pageHeight = 295 // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width
      let heightLeft = imgHeight
      let position = 0
      
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
      heightLeft -= pageHeight
      
      while (heightLeft >= 0) {
        position = heightLeft - imgHeight
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
        heightLeft -= pageHeight
      }
      
      return pdf.output('blob')
    }
    
    // Create text-based PDF if no element capture
    const pdf = new jsPDF()
    const margin = 20
    let y = margin
    
    // Title
    pdf.setFontSize(20)
    pdf.setFont('helvetica', 'bold')
    pdf.text('ARV Analysis Report', margin, y)
    y += 15
    
    // Property Info
    pdf.setFontSize(14)
    pdf.text('Property Information', margin, y)
    y += 8
    
    pdf.setFontSize(10)
    pdf.setFont('helvetica', 'normal')
    const propertyLines = [
      `Address: ${data.property.address}`,
      `City: ${data.property.city}, ${data.property.state} ${data.property.zip}`,
      `Square Feet: ${data.property.sqft?.toLocaleString() || 'N/A'}`,
      `Bedrooms: ${data.property.bedrooms || 'N/A'}`,
      `Bathrooms: ${data.property.bathrooms || 'N/A'}`,
      `Year Built: ${data.property.yearBuilt || 'N/A'}`
    ]
    
    propertyLines.forEach(line => {
      pdf.text(line, margin, y)
      y += 5
    })
    
    y += 10
    
    // ARV Calculation
    pdf.setFontSize(14)
    pdf.setFont('helvetica', 'bold')
    pdf.text('ARV Calculation', margin, y)
    y += 8
    
    pdf.setFontSize(10)
    pdf.setFont('helvetica', 'normal')
    const methodLabel = data.calculation.method.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())
    const calcLines = [
      `Method: ${methodLabel}`,
      `Base ARV: ${formatCurrencyText(data.calculation.baseArv)}`,
      `Feature Adjustment: ${data.calculation.adjustments.feature >= 0 ? '+' : ''}${formatCurrencyText(data.calculation.adjustments.feature)}`,
      `Condition Adjustment: ${data.calculation.adjustments.condition >= 0 ? '+' : ''}${formatCurrencyText(data.calculation.adjustments.condition)}`,
      ``,
      `FINAL ARV: ${formatCurrencyText(data.calculation.finalArv)}`
    ]
    
    calcLines.forEach(line => {
      if (line === '') {
        y += 3
        return
      }
      if (line.startsWith('FINAL ARV:')) {
        pdf.setFont('helvetica', 'bold')
      }
      pdf.text(line, margin, y)
      pdf.setFont('helvetica', 'normal')
      y += 5
    })
    
    // Add more content as needed...
    
    return pdf.output('blob')
  } catch (error) {
    console.error('Failed to generate PDF:', error)
    return null
  }
}

// Email integration (basic mailto link)
export function generateEmailLink(data: ARVReportData, subject?: string): string {
  const defaultSubject = `ARV Analysis - ${data.property.address}`
  const body = encodeURIComponent(generateARVSummary(data))
  return `mailto:?subject=${encodeURIComponent(subject || defaultSubject)}&body=${body}`
}

// Transform component data into export format
export function prepareARVReportData(
  propertyLead: PropertyLead,
  _marketAnalysis: MarketAnalysis | null,
  comps: Comp[],
  calculatedArv: number | null,
  method: ArvMethod,
  featureAdjustment: number,
  conditionAdjustment: number,
  confidenceScore: number,
  notes: string
): ARVReportData {
  return {
    property: {
      id: propertyLead.id,
      address: propertyLead.address,
      city: propertyLead.city,
      state: propertyLead.state,
      zip: propertyLead.zip,
      sqft: propertyLead.sqft,
      bedrooms: propertyLead.bedrooms,
      bathrooms: propertyLead.bathrooms,
      yearBuilt: propertyLead.year_built
    },
    calculation: {
      method,
      baseArv: (calculatedArv || 0) - featureAdjustment - conditionAdjustment,
      adjustments: {
        feature: featureAdjustment,
        condition: conditionAdjustment
      },
      finalArv: calculatedArv || 0,
      confidence: {
        score: confidenceScore,
        breakdown: {
          compCount: comps.length >= 3 ? 25 : comps.length === 2 ? 15 : comps.length === 1 ? 5 : 0,
          recency: 0, // Calculate based on actual dates
          priceVariance: 0, // Calculate based on actual variance  
          adjustmentSpread: 0 // Calculate based on actual adjustments
        }
      }
    },
    comps: comps.map(comp => ({
      address: comp.address,
      salePrice: Number(comp.sale_price) || 0,
      saleDate: comp.sale_date || '',
      bedrooms: comp.bedrooms,
      bathrooms: comp.bathrooms,
      sqft: comp.sqft,
      pricePerSqft: comp.price_per_sqft,
      totalAdjustment: (Number(comp.adjustment_sqft) || 0) +
                      (Number(comp.adjustment_bedrooms) || 0) +
                      (Number(comp.adjustment_bathrooms) || 0) +
                      (Number(comp.adjustment_condition) || 0) +
                      (Number(comp.adjustment_age) || 0) +
                      (Number(comp.adjustment_other) || 0)
    })),
    notes,
    generatedAt: new Date().toISOString(),
    generatedBy: 'ARV Calculator'
  }
}